### ISSUE TITLE
Try making all tasks in tests step functional

### ISSUE THREAD

**Issue by verbruggenalex** [verbruggenalex/grumphp-stack#1]
These are all running tasks at the moment. The ones without ✔ should be made functional.

Running task 1/28: atoum... ✔
Running task 2/28: brunch... 
Running task 3/28: composer... ✔
Running task 4/28: composer_normalize... ✔
Running task 5/28: eslint... 
Running task 6/28: file_size... ✔
Running task 7/28: gherkin... 
Running task 8/28: git_branch_name... ✔
Running task 9/28: grunt... 
Running task 10/28: gulp... 
Running task 11/28: jsonlint... ✔
Running task 12/28: paratest... ✔
Running task 13/28: phpcpd... ✔
Running task 14/28: phpcs... ✔
Running task 15/28: phplint... ✔
Running task 16/28: phpmd... ✔
Running task 17/28: phpparser... ✔
Running task 18/28: phpspec... ✔
Running task 19/28: phpstan... ✔
Running task 20/28: phpversion... 
Running task 21/28: progpilot... ✔
Running task 22/28: robo... ✔
Running task 23/28: securitychecker... 
Running task 24/28: shell... ✔
Running task 25/28: tester... 
Running task 26/28: twigcs... 
Running task 27/28: xmllint... ✔
Running task 28/28: yamllint... ✔

These tasks have been commented out because they were throwing errors and should be individually checked:

```yaml
# grumphp.yml
grumphp:
    ascii:
        failed: ~
        succeeded: ~
    tasks:
        # ant: ~
        # behat: ~
        # clover_coverage: ~
        # codeception: ~
        # composer_require_checker: ~
        # composer_script: ~
        # deptrac: ~
        # doctrine_orm: ~
        # ecs: ~
        # infection: ~
        # kahlan: ~
        # make: ~
        # npm_script: ~
        # pest: ~
        # phan: ~
        # phing: ~
        # php7cc: ~
        # phpcsfixer: ~
        # phpmnd: ~
        # phpunit: ~
        # phpunitbridge: ~
        # psalm: ~    
```
